### PR TITLE
link to new, recommended resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Please see diff & https://www.doi.org/doi_handbook/3_Resolution.html#3.8, and consider updating the link in the repo website setting as well :-)

### CODE REVIEW

**Comment by rokuwaki** [comment]
Thank you so much for the request!
I am very sorry for the delayed response. I merged your request!

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Comment by katrinleinweber** [comment]
Oh! The last link broke because of a typo of mine: `/.doi`. But your follow-on commit from the web-interface introduced the `dx` again. Maybe due to a cached text field in the browser?

**Comment by rokuwaki** [comment]
Sorry for the mess! Now I fixed the issues on URL, and I hope it would be OK...

**Comment by katrinleinweber** [comment]
My apologies for the initial typo! 🙏

**Comment by rokuwaki** [comment]
Please do not apologize! Thank you very much for all your contributions🤝

2018年1月12日(金) 1:21 Katrin Leinweber <notifications@github.com>:

**Pull request merged**
